# Sniperkit-Bot
# - Status: analyzed

sudo: required
services:
  - docker
cache:
  bundler: false
  directories:
  - .build-cache          # images.txt
# Handle git submodules yourself
git:
    submodules: false
# Do a github login using token
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
  - "docker login -u=\"${DOCKER_USERNAME}\" -p=\"${DOCKER_PASSWORD}\""

script: 
  - touch flogo-services.tgz
  - tar cvfz flogo-services.tgz --exclude=flogo-services.tgz .
  - find . -not -name "flogo-services.tgz" -not  -name "\." -not -name "\.\."  -print0 | xargs -0 rm -rf --
  - "git ls-remote --exit-code https://github.com/TIBCOSoftware/flogo-cicd.git ${TRAVIS_BRANCH} ;
    if [ $? -eq 0 ]; then 
        echo \"Branch ${TRAVIS_BRANCH} found on flogo-cicd\" ;
        git clone https://github.com/TIBCOSoftware/flogo-cicd.git --branch ${TRAVIS_BRANCH} --single-branch flogo-cicd ;
    else 
        echo \"Branch ${TRAVIS_BRANCH} not found on flogo-cicd using master\" ;
        git clone https://github.com/TIBCOSoftware/flogo-cicd.git flogo-cicd ;
    fi"
  - pushd flogo-cicd/docker/flow-service
  - ./build-flow-service.sh
  - popd
  - pushd flogo-cicd/docker/state-service
  - ./build-state-service.sh
  - popd
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
after_success:
  - "if [ \"${TRAVIS_BRANCH}\" == \"master\" ]; then
    source ${TRAVIS_BUILD_DIR}/flogo-cicd/scripts/init.sh ;
    flogo::module::postbuild flogo-services flow-service ;
    flogo::module::postbuild flogo-services state-service ;
    fi"
